#pragma config(Sensor, in1,    liftpot,        sensorPotentiometer)
#pragma config(Sensor, in2,    ClawPot,        sensorPotentiometer)
#pragma config(Sensor, in8,    GYREEEEE,       sensorGyro)
#pragma config(Sensor, dgtl1,  SAencoder,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           DO_NUT_USE_Indeed, tmotorNone, openLoop)
#pragma config(Motor,  port2,           MGLiftMotorR,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LDMotors,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RSAMotor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LSAMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RDMotors,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           ClawMotor,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          MGLiftMotorL,  tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int dist;
bool driving =  false;

task drive()
{
	driving = true;


	SensorValue[LeftEncoder]=0;

	if(dist>0)
	{
		motor[RDMotors]= 127;
		motor[LDMotors]=127;
		while(SensorValue[LeftEncoder] < dist) wait1Msec(5);
		motor[RDMotors]=0;
		motor[LDMotors]=0;

	}
	else
	{
		motor[RDMotors]= -127;
		motor[LDMotors]=-127;
		while(SensorValue[LeftEncoder] > dist) wait1Msec(5);
		motor[RDMotors]=0;
		motor[LDMotors]=0;

	}
	driving = false;
}
///////////////////////////////////////////////


int SAtime;
bool SAmoving = false;
bool SAback;
task MoveSA()
{
	SAmoving = true;


	if(SABack)
	{
		motor[LSAMotor]=-127;
		motor[RSAMotor]=-127;
		wait1Msec(SAtime);
		motor[LSAMotor]=0;
		motor[RSAMotor]=0;
	}
	else
	{
		motor[LSAMotor]=127;
		motor[RSAMotor]=127;
		wait1Msec(SAtime);
		motor[LSAMotor]=0;
		motor[RSAMotor]=0;
	}
	SAmoving=false;

}
///////////////////////////////////////////////////////////////
int lifttime;
bool in;
bool lifting = false;

task MG()
{
	lifting = true;
	if(in)
	{
		motor[MGLiftMotorL]=127;
		motor[MGLiftMotorR]=127;
		wait1Msec(lifttime);
		motor[MGLiftMotorL]=0;
		motor[MGLiftMotorR]=0;
	}
	else
	{
		motor[MGLiftMotorL]=-127;
		motor[MGLiftMotorR]=-127;
		wait1Msec(lifttime);
		motor[MGLiftMotorL]=0;
		motor[MGLiftMotorR]=0;
	}
	lifting = false;
}
///////////////////////////////////////////////////
bool suck;
int sucktime;
bool grabbing = false;

task claw()
{
	grabbing = true;
	if(suck)
	{
		motor[ClawMotor]=-127;
		wait1Msec(sucktime);
		motor[ClawMotor]=0;
	}
	else
	{
		motor[ClawMotor]=127;
		wait1Msec(sucktime);
		motor[ClawMotor]=0;


	}
	grabbing = false;
}
/////////////////////////////////
int turncount;
task rotate()
{
	driving = true;


	SensorValue[LeftEncoder]=0;

	if(turncount>0)
	{
		motor[RDMotors]= -127;
		motor[LDMotors]=127;
		while(SensorValue[LeftEncoder] < turncount) wait1Msec(5);
		motor[RDMotors]=0;
		motor[LDMotors]=0;

	}
	else
	{
		motor[RDMotors]= 127;
		motor[LDMotors]=-127;
		while(SensorValue[LeftEncoder] > turncount) wait1Msec(5);
		motor[RDMotors]=0;
		motor[LDMotors]=0;

	}
	driving = false;
}

int lcount;
bool expanding = false;
bool up;
task expand()
{
	expanding = true;
	if(up)
	{
		motor[RLift]=127;
		motor[LLift]=127;
		while(SensorValue[liftpot] < lcount) wait1Msec(10);
		motor[RLift]=0;
		motor[LLift]=0;
	}
	else
	{
		motor[RLift]=-127;
		motor[LLift]=-127;
		while(SensorValue[liftpot] > lcount) wait1Msec(10);
		motor[RLift]=0;
		motor[LLift]=0;
	}
	expanding = false;
}

int count;
int height[4]={120,400,600,1000};
int heightCount;
task main()
{

	if(vexRT[Btn7UXmtr2] == 1)
	{

		if(count<=4)
		{
			/// suck preload
			suck=true;
			sucktime=500;
			startTask(claw);
			while(grabbing) wait1Msec(10);
			///brings swing arm back and spits cone on MG
			SAback=false;
			SAtime=750;
			startTask(SAmoving);
			suck=false;
			sucktime=1250;
			startTask(claw);
			while(SAmoving) wait10Msec(10);
			suck=false;
			sucktime=1250;
			startTask(claw);
			while(grabbing) wait1Msec(10);
			SAback=true;
			SAtime=750;
			startTask(SAmoving);
			while(SAmoving) wait10Msec(10);
			count++;

		}

		else if(count>4)
		{
			if(count<6)
			{
				heightcount=0;
			}
			if(count>=6 && count<8)
			{
				heightCount=1;
			}
			if(count>=9 &&count<11)
			{
				heightCount=1;
			}
			int x=height[heightCount];
			/// suck preload,lifts 4bar to desired height
			suck=true;
			sucktime=500;
			startTask(claw);
			while(grabbing) wait1Msec(10);
			up=true;
			lcount=x;
			startTask(expand);
			while(expanding) wait1Msec(10);
			///brings swing arm back and spits cone on MG
			SAback=false;
			SAtime=750;
			startTask(SAmoving);
			suck=false;
			sucktime=1250;
			startTask(claw);
			while(SAmoving) wait10Msec(10);
			suck=false;
			sucktime=1250;
			startTask(claw);
			while(grabbing) wait1Msec(10);
			SAback=true;
			SAtime=750;
			startTask(SAmoving);
			while(SAmoving) wait10Msec(10);



			count++;
		}
	}
}
