#pragma config(Sensor, dgtl1,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncoder,       sensorQuadEncoder)
#pragma config(Motor,  port1,           RExtraBarMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RBack,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RBarMotors,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LClawMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RClawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LBack,	       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LFront,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          LExtraBarMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
//http://help.robotc.net/WebHelpVEX/Content/Resources/topics/ROBOTC_Interface/Toolbars/Toolbars.htm
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	wait1Msec(5);
}
//----------------------------------------------------------------
int count;
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	//Declare count variable to keep track of our choice

	count=0;

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	bLCDBacklight=true;
	while(vexRT[Btn8R] != 1)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Autonomous 1");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press

			if(vexRT[Btn7U] == 1)
			{
				waitForRelease();
				count = 1;
			}
			else if(vexRT[Btn7D] == 1)
			{
				waitForRelease();
				count = 2;
			}
			else if(vexRT[Btn7R] == 1)
			{
				waitForRelease();
				count = 3;
			}
			else if(vexRT[Btn8L] == 1)
			{
				waitForRelease();
				count = 4;
			}
			else if(vexRT[Btn8U] == 1)
			{
				waitForRelease();
				count = 5;
			}
			else if(vexRT[Btn8D] == 1)
			{
				waitForRelease();
				count = 6;
			}

			break;

		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Autonomous 2");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press

			if(vexRT[Btn7L] == 1)
			{
				waitForRelease();
				count = 0;
			}
			else if(vexRT[Btn7D] == 1)
			{
				waitForRelease();
				count = 2;
			}
			else if(vexRT[Btn7R] == 1)
			{
				waitForRelease();
				count = 3;
			}
			else if(vexRT[Btn8L] == 1)
			{
				waitForRelease();
				count = 4;
			}
			else if(vexRT[Btn8U] == 1)
			{
				waitForRelease();
				count = 5;
			}
			else if(vexRT[Btn8D] == 1)
			{
				waitForRelease();
				count = 6;
			}

			break;

		case 2:
			//Display third choice
			displayLCDCenteredString(0, "Autonomous 3");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press

			if(vexRT[Btn7L] == 1)
			{
				waitForRelease();
				count = 0;
			}
			else if(vexRT[Btn7U] == 1)
			{
				waitForRelease();
				count = 1;
			}
			else if(vexRT[Btn7R] == 1)
			{
				waitForRelease();
				count = 3;
			}
			else if(vexRT[Btn8L] == 1)
			{
				waitForRelease();
				count = 4;
			}
			else if(vexRT[Btn8U] == 1)
			{
				waitForRelease();
				count = 5;
			}
			else if(vexRT[Btn8D] == 1)
			{
				waitForRelease();
				count = 6;
			}

			break;

		case 3:
			//Display fourth choice
			displayLCDCenteredString(0, "Autonomous 4");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press

			if(vexRT[Btn7L] == 1)
			{
				waitForRelease();
				count = 0;
			}
			else if(vexRT[Btn7U] == 1)
			{
				waitForRelease();
				count = 1;
			}
			else if(vexRT[Btn7D] == 1)
			{
				waitForRelease();
				count = 2;
			}
			else if(vexRT[Btn8L] == 1)
			{
				waitForRelease();
				count = 4;
			}
			else if(vexRT[Btn8U] == 1)
			{
				waitForRelease();
				count = 5;
			}
			else if(vexRT[Btn8D] == 1)
			{
				waitForRelease();
				count = 6;
			}

			break;

		case 4:
			//Display fifth choice
			displayLCDCenteredString(0, "Autonomous 5");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press

			if(vexRT[Btn7L] == 1)
			{
				waitForRelease();
				count = 0;
			}
			else if(vexRT[Btn7U] == 1)
			{
				waitForRelease();
				count = 1;
			}
			else if(vexRT[Btn7D] == 1)
			{
				waitForRelease();
				count = 2;
			}
			else if(vexRT[Btn7R] == 1)
			{
				waitForRelease();
				count = 3;
			}
			else if(vexRT[Btn8U] == 1)
			{
				waitForRelease();
				count = 5;
			}
			else if(vexRT[Btn8D] == 1)
			{
				waitForRelease();
				count = 6;
			}

			break;

		case 5:
			//Display sixth choice
			displayLCDCenteredString(0, "Autonomous 6");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press

			if(vexRT[Btn7L] == 1)
			{
				waitForRelease();
				count = 0;
			}
			else if(vexRT[Btn7U] == 1)
			{
				waitForRelease();
				count = 1;
			}
			else if(vexRT[Btn7D] == 1)
			{
				waitForRelease();
				count = 2;
			}
			else if(vexRT[Btn7R] == 1)
			{
				waitForRelease();
				count = 3;
			}
			else if(vexRT[Btn8L] == 1)
			{
				waitForRelease();
				count = 4;
			}
			else if(vexRT[Btn8D] == 1)
			{
				waitForRelease();
				count = 6;
			}

			break;

		case 6:
			//Display seventh choice
			displayLCDCenteredString(0, "Autonomous 7");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press

			if(vexRT[Btn7L] == 1)
			{
				waitForRelease();
				count = 0;
			}
			else if(vexRT[Btn7U] == 1)
			{
				waitForRelease();
				count = 1;
			}
			else if(vexRT[Btn7D] == 1)
			{
				waitForRelease();
				count = 2;
			}
			else if(vexRT[Btn7R] == 1)
			{
				waitForRelease();
				count = 3;
			}
			else if(vexRT[Btn8L] == 1)
			{
				waitForRelease();
				count = 4;
			}
			else if(vexRT[Btn8U] == 1)
			{
				waitForRelease();
				count = 5;
			}

			break;

		default:
			count = 0;
			break;
		}

		//------------- End of User Interface Code ---------------------
	}
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	bDisplayCompetitionStatusOnLcd = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...



}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here
	// ..........................................................................
	//------------- Beginning of Robot Movement Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Autonomous 1");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 200 milliseconds



		///////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Automous 2");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 200 milliseconds



		///////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 2:
		//If count = 2, run the code correspoinding with choice 3
		displayLCDCenteredString(0, "Autonomous 3");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 200 milliseconds



		///////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 3:
		//If count = 3, run the code correspoinding with choice 4
		displayLCDCenteredString(0, "Autonomous 4");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 200 milliseconds



		///////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 4:
		//If count = 4, run the code correspoinding with choice 5
		displayLCDCenteredString(0, "Autonomous 5");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 200 milliseconds




		///////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 5:
		//If count = 5, run the code correspoinding with choice 6
		displayLCDCenteredString(0, "Autonomous 6");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 200 milliseconds



		///////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 6:
		//If count = 6, run the code correspoinding with choice 7
		displayLCDCenteredString(0, "Autonomous 7");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 200 milliseconds



		///////////////////////////////////////////////////////////////////////////////////////////////
		break;

	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!");
		break;
	}
	//------------- End of Robot Movement Code -----------------------

}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{



	}
}
