#pragma config(Sensor, dgtl1,  redLEDMain,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  yellowLEDMain,  sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  greenLEDMain,   sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  redLEDSide,     sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  yellowLEDSide,  sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  greenLEDSide,   sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  limitSwitch1,     sensorTouch)
#pragma config(Sensor, dgtl8,  limitSwitch2,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:Terry Traffic Tamer
Team Members:Damico T., Angel B., Tristan W., Nevaeh S.
Date:1/5/17
Section:


Task Description:
Your mission is to install a traffic light control system that will enable you to keep
traffic moving smoothly. One side of the light system will remain green until a car
approaches from a side street. When a car approaches from the side street (touch sensor
1) the main light system will change to yellow for 5 seconds then change to red while the
side street light turns green when its safe to go. After the car clears traffic, (touch sensor
2), the light system on the side street will continu throught the pattern stated above while the
main street remains red, Upon which the main street will then return to green.


Pseudocode:
green led turn on
red led turn on
limit switch is pressed
green led switched to yellow
wait 5 seconds on the yellow light
yellow switches to red
red switches to green
second limit switch is triggered
green switches to yellow
wait 5 seconds
yellow switches to red
red switches to green
sequence ends and loop sets back to beggining


*/


task main()
{                                    	 //Program begins, insert code within curly braces
	while(true)
	{
		turnLEDOn(greenLEDMain);						//turn green led on
		turnLEDOn(redLEDSide);							//turn red led on
		untilBump(limitSwitch1, 50);				//wait until limit is pressed
		turnLEDOff(greenLEDMain);						//turn green led off
		turnLEDOn(yellowLEDMain);						//turn yellow led on
		wait(5);														//wait 5 seconds
		turnLEDOff(yellowLEDMain);					//turn yellow led off
		turnLEDOff(redLEDSide);							//turn red led off
		turnLEDOn(redLEDMain);							//turn red led on
		turnLEDOn(greenLEDSide);						//turn green led on
		untilBump(limitSwitch2, 50);				//wait until second limit is pressed
		turnLEDOff(greenLEDSide);						//turn greeb led off
		turnLEDOn(yellowLEDSide);						//turn yellow led on
		wait(5);														//wait 5 seconds
		turnLEDOff(redLEDMain);							//turn red led off
		turnLEDOff(yellowLEDSide);					//turn yellow led off
		turnLEDOn(greenLEDMain);						//turn green led on
		turnLEDOn(redLEDSide);							//turn red led on


	}
}
