#pragma config(Sensor, dgtl1,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11,  Sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           RExtraBarMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RBack,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RBarMotors,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LClawMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RClawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LBack,	       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LFront,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          LExtraBarMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------
int count;
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	const short leftButton = 1;
	const short centerButton = 2;
	const short rightButton = 4;


	//Declare count variable to keep track of our choice

	count=0;

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	bLCDBacklight=true;
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Left Cube");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 5;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 1:
			//Display fifth choice
			displayLCDCenteredString(0, "Mid-Cube Left");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 2:
			//Display second choice
			displayLCDCenteredString(0, "Non-Cube");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 3:
			//Display sixth choice
			displayLCDCenteredString(0, "Mid-Cube Right");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 4:
			//Display third choice
			displayLCDCenteredString(0, "Right Cube");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 5:
			//Display fourth choice
			displayLCDCenteredString(0, "Free Movement");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;

		default:
			count = 0;
			break;
		}

		//------------- End of User Interface Code ---------------------
	}
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	bDisplayCompetitionStatusOnLcd = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...



}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here
	// ..........................................................................
	//------------- Beginning of Robot Movement Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 3, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Free Movement");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	/*

				//////
				//////

	*/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 1:
		//If count = 3, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Free Movement");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	/*

				//////
				//////

	*/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 2:
		//If count = 3, run the code correspoinding with choice 3
		displayLCDCenteredString(0, "Free Movement");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	/*

				//////
				//////

	*/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 3:
		//If count = 3, run the code correspoinding with choice 4
		displayLCDCenteredString(0, "Free Movement");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	/*

				//////
				//////

	*/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 4:
		//If count = 3, run the code correspoinding with choice 5
		displayLCDCenteredString(0, "Free Movement");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	/*

				//////
				//////

	*/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 5:
		//If count = 3, run the code correspoinding with choice 6
		displayLCDCenteredString(0, "Free Movement");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	/*

				//////
				//////

	*/
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!");
		break;
	}
	//------------- End of Robot Movement Code -----------------------

}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		motor[port2]=vexRT[Ch2];
		motor[port3]=vexRT[Ch2];
		motor[port8]=vexRT[Ch3];
		motor[port9]=vexRT[Ch3];


		////////////////////////////////////////////////////////////////////

		if(vexRT[Btn6U] == 1)       //motor code for bar lift going up
		{
			motor[port4] = -123;				//motor code for port 4 going up
			motor[port5] = -123;				//motor code for port 5 going up
			motor[port1] = -123;       //motor code for port 1 going up
			motor[port10] = -123;      //motor code for port 10 going up

		}

		else if(vexRT[Btn6D] == 1)	//motor code for bar lift going down
		{
			motor[port4] = 123;			//motor code for port 4 going down
			motor[port5] = 123;			//motor code for port 5 going down
			motor[port1] = 123;      //motor code for port 1 going down
			motor[port10] = 123;  	  //motor code for port 10 going down

		}

		else												//stop for bar lift
		{
			motor[port4] = 0;         // end motor code for port 4
			motor[port5] = 0;					// end motor code for port 5
			motor[port1] = 0;         // end motor code for port 1
			motor[port10] = 0;        // end motor code for port 10


		}


		////////////////////////////////////////////////////////////////////

		if(vexRT[Btn5U] == 1)       //motor code for claw opening
		{
			motor[port6] = 127;				//motor code for port 6 opening
			motor[port7] = 127;				//motor code for port 7 opening

		}

		else if(vexRT[Btn5D] == 1)	//motor code for claw closing
		{
			motor[port6] = -127;				//motor code for port 6 closing
			motor[port7] = -127;				//motor code for port 7 closing

		}

		else												//stop for claw motors
		{
			motor[port6] = 0;         // end motor code for port 6
			motor[port7] = 0;					// end motor code for port 7


		}
	}
}
/*
http://www.vexmen.com/2011/11/whats-your-robot-drive-style/
https://www.vexforum.com/index.php/6146-robotc-programming-tips/p3#p54732




*/
