#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, armEncoder,     sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, driveRight, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void base(int speed)
{
	motor[rightMotor] = speed;
	motor[leftMotor] = speed;
}

task main()
{
	int speed;
	speed = 96;
	/*
	1. forward to right blue mobile goal
	2. arm down to top of goal
	3. drop cone on goal


	*/


	//1. forward to right blue mobile goal
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
	untilTouch(touchSensor);
	while (SensorValue[rightEncoder] < 1050)
	{
		base(speed);

	}

	//2. arm down to top of goal
	motor[armMotor] = -96;
	wait1Msec(300);
	motor[armMotor] = 0;

	//3. drop cone on goal



	/*
	motor[clawMotor] = 64;
	motor[armMotor] = 96;
	wait1Msec(500);

	motor[armMotor] = 0;

	motor[leftMotor] = 96;
	motor[rightMotor] = 64;
	wait1Msec(1000);

	motor[leftMotor] = 96;
	motor[rightMotor] = 96;
	wait1Msec(2000);

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	motor[armMotor] = -96;
	wait1Msec(500);

	motor[armMotor] = 0;
	motor[leftMotor] = -96;
	motor[rightMotor] = -96;
	wait1Msec(2000);

	motor[leftMotor] = 0;
	motor[leftMotor] = 0;

	*/
}
