#pragma config(Motor,  port1,           leftGrip,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftArmtop,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftArmbottom, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightFront,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightArmtop,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightArmbottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightGrip,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Controller Code//

task main()
{
	while(1==1)//infinite loop (true)
	{

		///////////Base Motor Control///////////////
		//Left Side///
		motor[leftFront] = vexRT[Ch3];
		motor[leftBack] = vexRT[Ch3];
		//Right Side//
		motor[rightFront] = vexRT[Ch2];
		motor[rightBack] = vexRT[Ch2];

		////////Arm Controls///////
		if(vexRT[Btn6U]==1)
		{
			motor[rightArmtop]= 100;	//Arms moves up
			motor[leftArmtop]= 100;
			motor[rightArmbottom]= 100;
			motor[leftArmbottom]= 100;
		}
		else if(vexRT[Btn6D]==1)
		{
			motor[rightArmtop]= -100;	// Arms move down
			motor[leftArmbottom]= -100;
			motor[rightArmtop]=-100;
			motor[leftArmbottom]=-100;
		}
		else
		{
			motor[rightArmtop]= 0;
			motor[leftArmtop]= 0;
			motor[rightArmbottom]=0;
			motor[leftArmbottom]=0;
		}

		/////////Grip Control//////////
		if(vexRT[Btn5U]==1)
		{
			motor[rightGrip  ]= 127;	//Arms moves up
			motor[leftGrip]= 127;
		}
		else if(vexRT[Btn5D]==1)
		{
			motor[rightGrip]= -127;	// Arms move down
			motor[leftGrip]= -127;
		}
		else
		{
			motor[rightGrip]= 0;
			motor[leftGrip]= 0;
		}

	} //closes the while loop
} //closes the task main
