#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl10, redLED,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, yellowLED,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, greenLED,       sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title: motor exercise 1
Team Members:
Date:
Section:


Task Description:

Psuedocode:
*/

task main()
{
	untilBump(dgtl2, 100);
	startMotor(2, 127);
	startMotor(3, 127);
	untilBump(dgtl2, 100);
	stopMotor(2);
	untilBump(dgtl1, 100);
	stopMotor(3);


}
