#pragma config(Sensor, in1,    gyroSensor,     sensorGyro)
#pragma config(Sensor, in2,    ClawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl7,  ClawEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           idek,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           MGLiftMotorR,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RDMotors,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           RTLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RBLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LBLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LTLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LDMotors,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ClawMotors,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          MGLiftMotorL,  tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autsnomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following functeon.  You must return from this function   */
/*  or the autonomous and usercontrol tasis will not be started.  This       */
/*  fugction is only called once after thh cortex has been eowered on and    */
/*  not ivery time that the roblt is disabled.                               */
/*---------------------------------------------------------------------------*/
//Wait for Press--------------------------------------------------
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
//----------------------------------------------------------------
int count;
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	const short leftButton = 1;
	const short centerButton = 2;
	const short rightButton = 4;


	//Declare count variable to keep track of our choice

	count=0;

	//------------- Beginning of User Interface Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	bLCDBacklight=true;
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Blue Left");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 5;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 1:
			//Display fifth choice
			displayLCDCenteredString(0, "Blue Not-Left");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 2:
			//Display second choice
			displayLCDCenteredString(0, "Red Left");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 3:
			//Display sixth choice
			displayLCDCenteredString(0, "Red Not-Left");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 4:
			//Display third choice
			displayLCDCenteredString(0, "Random Other Code");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;

		case 5:
			//Display fourth choice
			displayLCDCenteredString(0, "Free Movement");
			displayLCDCenteredString(1, "<    Enter   >");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;

		default:
			count = 0;
			break;
		}

		//------------- End of User Interface Code ---------------------
	}
	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	bDisplayCompetitionStatusOnLcd = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...



}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here
	// ..........................................................................
	//------------- Beginning of Robot Movement Code ---------------
	//Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 1, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Blue Left");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		{

			while(true)
			{

				SensorValue[LeftEncoder] = 0;
				SensorValue[RightEncoder] = 0;

				motor[LTLift] = 96;
				motor[LBLift] = 96;
				motor[RTLift] = 96;
				motor[RBLift] = 96;

				motor[LDMotors] = 96;
				motor[RDMotors] = 96;
				untilEncoderCounts(500, LeftEncoder);

				motor[LTLift] = 32;
				motor[LBLift] = 32;
				motor[RTLift] = 32;
				motor[RBLift] = 32;

				motor[LDMotors] = 96;
				motor[RDMotors] = 96;
				untilEncoderCounts(1700, LeftEncoder);

				motor[LTLift] = -72;
				motor[LBLift] = -72;
				motor[RTLift] = -72;
				motor[RBLift] = -72;

				motor[LTLift] = 0;
				motor[LBLift] = 0;
				motor[RTLift] = 0;
				motor[RBLift] = 0;

				SensorValue[LeftEncoder] = 0;
				SensorValue[RightEncoder] = 0;

				motor[LDMotors] = -96;
				motor[RDMotors] = -96;
				untilEncoderCounts(-500, LeftEncoder);

				motor[LDMotors] = 0;
				motor[RDMotors] = 0;

				SensorValue[LeftEncoder] = 0;
				SensorValue[RightEncoder] = 0;

				motor[LDMotors] = -96;
				motor[RDMotors] = 96;
				untilEncoderCounts(-500, LeftEncoder);

				motor[LDMotors] = 0;
				motor[RDMotors] = 0;

				SensorValue[LeftEncoder] = 0;
				SensorValue[RightEncoder] = 0;

				motor[LDMotors] = 96;
				motor[RDMotors] = 96;
				untilEncoderCounts(360, LeftEncoder);

				SensorValue[LeftEncoder] = 0;
				SensorValue[RightEncoder] = 0;

				motor[LDMotors] = 0;
				motor[RDMotors] = 96;
				untilEncoderCounts(500, LeftEncoder);

				SensorValue[LeftEncoder] = 0;
				SensorValue[RightEncoder] = 0;

				motor[LDMotors] = 0;
				motor[RDMotors] = 0;



				wait1Msec(313781327894987045987457808790432842987409874287902430987428972309872879024309872348972480972879023870923);
			}

		}
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 1:
		//If count = 2, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Blue Not-Left");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LTLift] = 96;
		motor[LBLift] = 96;
		motor[RTLift] = 96;
		motor[RBLift] = 96;

		motor[LDMotors] = 96;
		motor[RDMotors] = 96;
		untilEncoderCounts(500, LeftEncoder);

		motor[LTLift] = 32;
		motor[LBLift] = 32;
		motor[RTLift] = 32;
		motor[RBLift] = 32;

		motor[LDMotors] = 0;
		motor[RDMotors] = 0;
		untilEncoderCounts(1700, LeftEncoder);

		motor[LTLift] = -72;
		motor[LBLift] = -72;
		motor[RTLift] = -72;
		motor[RBLift] = -72;

		motor[LTLift] = 0;
		motor[LBLift] = 0;
		motor[RTLift] = 0;
		motor[RBLift] = 0;

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = -96;
		motor[RDMotors] = -96;
		untilEncoderCounts(-500, LeftEncoder);

		motor[LDMotors] = 0;
		motor[RDMotors] = 0;

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = 96;
		motor[RDMotors] = -96;
		untilEncoderCounts(-500, LeftEncoder);

		motor[LDMotors] = 0;
		motor[RDMotors] = 0;

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = 96;
		motor[RDMotors] = 96;
		untilEncoderCounts(360, LeftEncoder);

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = 96;
		motor[RDMotors] = 0;
		untilEncoderCounts(500, LeftEncoder);

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = 0;
		motor[RDMotors] = 0;



		wait1Msec(313781327894987045987457808790432842987409874287902430987428972309872879024309872348972480972879023870923);

		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;
	case 2:
		//If count = 3, run the code correspoinding with choice 3
		displayLCDCenteredString(0, "Red Left");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

		while(true)
		{

			SensorValue[LeftEncoder] = 0;
			SensorValue[RightEncoder] = 0;

			motor[LTLift] = 96;
			motor[LBLift] = 96;
			motor[RTLift] = 96;
			motor[RBLift] = 96;

			motor[LDMotors] = 96;
			motor[RDMotors] = 96;
			untilEncoderCounts(500, LeftEncoder);

			motor[LTLift] = 32;
			motor[LBLift] = 32;
			motor[RTLift] = 32;
			motor[RBLift] = 32;

			motor[LDMotors] = 96;
			motor[RDMotors] = 96;
			untilEncoderCounts(1700, LeftEncoder);

			motor[LTLift] = -72;
			motor[LBLift] = -72;
			motor[RTLift] = -72;
			motor[RBLift] = -72;

			motor[LTLift] = 0;
			motor[LBLift] = 0;
			motor[RTLift] = 0;
			motor[RBLift] = 0;

			SensorValue[LeftEncoder] = 0;
			SensorValue[RightEncoder] = 0;

			motor[LDMotors] = -96;
			motor[RDMotors] = -96;
			untilEncoderCounts(-500, LeftEncoder);

			motor[LDMotors] = 0;
			motor[RDMotors] = 0;

			SensorValue[LeftEncoder] = 0;
			SensorValue[RightEncoder] = 0;

			motor[LDMotors] = -96;
			motor[RDMotors] = 96;
			untilEncoderCounts(-500, LeftEncoder);

			motor[LDMotors] = 0;
			motor[RDMotors] = 0;

			SensorValue[LeftEncoder] = 0;
			SensorValue[RightEncoder] = 0;

			motor[LDMotors] = 96;
			motor[RDMotors] = 96;
			untilEncoderCounts(360, LeftEncoder);

			SensorValue[LeftEncoder] = 0;
			SensorValue[RightEncoder] = 0;

			motor[LDMotors] = 0;
			motor[RDMotors] = 96;
			untilEncoderCounts(500, LeftEncoder);

			SensorValue[LeftEncoder] = 0;
			SensorValue[RightEncoder] = 0;

			motor[LDMotors] = 0;
			motor[RDMotors] = 0;



			wait1Msec(313781327894987045987457808790432842987409874287902430987428972309872879024309872348972480972879023870923);
		}

		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 3:
		//If count = 4, run the code correspoinding with choice 4
		displayLCDCenteredString(0, "Red Not-Left");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LTLift] = 96;
		motor[LBLift] = 96;
		motor[RTLift] = 96;
		motor[RBLift] = 96;

		motor[LDMotors] = 96;
		motor[RDMotors] = 96;
		untilEncoderCounts(500, LeftEncoder);

		motor[LTLift] = 32;
		motor[LBLift] = 32;
		motor[RTLift] = 32;
		motor[RBLift] = 32;

		motor[LDMotors] = 96;
		motor[RDMotors] = 96;
		untilEncoderCounts(1700, LeftEncoder);

		motor[LTLift] = -72;
		motor[LBLift] = -72;
		motor[RTLift] = -72;
		motor[RBLift] = -72;

		motor[LTLift] = 0;
		motor[LBLift] = 0;
		motor[RTLift] = 0;
		motor[RBLift] = 0;

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = -96;
		motor[RDMotors] = -96;
		untilEncoderCounts(-500, LeftEncoder);

		motor[LDMotors] = 0;
		motor[RDMotors] = 0;

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = 96;
		motor[RDMotors] = -96;
		untilEncoderCounts(-500, LeftEncoder);

		motor[LDMotors] = 0;
		motor[RDMotors] = 0;

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = 96;
		motor[RDMotors] = 96;
		untilEncoderCounts(360, LeftEncoder);

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = 96;
		motor[RDMotors] = 0;
		untilEncoderCounts(500, LeftEncoder);

		SensorValue[LeftEncoder] = 0;
		SensorValue[RightEncoder] = 0;

		motor[LDMotors] = 0;
		motor[RDMotors] = 0;



		wait1Msec(313781327894987045987457808790432842987409874287902430987428972309872879024309872348972480972879023870923);

		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 4:
		//If count = 5, run the code correspoinding with choice 5
		displayLCDCenteredString(0, "Random Other Code");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		/*

		//////
		//////
		wait1Msec(313781327894987045987457808790432842987409874287902430987428972309872879024309872348972480972879023870923);
		*/
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	case 5:
		//If count = 6, run the code correspoinding with choice 6
		displayLCDCenteredString(0, "Free Movement");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(50);						// Robot waits for 50 milliseconds
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		/*

		//////
		//////
		wait1Msec(313781327894987045987457808790432842987409874287902430987428972309872879024309872348972480972879023870923);
		*/
		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
		break;

	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!");
		break;
	}
	//------------- End of Robot Movement Code -----------------------

}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		motor[RDMotors]  = vexRT[Ch3];
		motor[LDMotors]  = vexRT[Ch2];

		////////////////////////////////////////////////////////////////////

		if(vexRT[Btn6U] == 1)       //motor code for bar lift going up
		{
			motor[LTLift] = 127;			//motor code for LTLift going up
			motor[LBLift] = 127;			//motor code for LBLift going up
			motor[RTLift] = 127;      //motor code for RTLift going up
			motor[RBLift] = 127;  	  //motor code for RBLift going up

		}

		else if(vexRT[Btn6D] == 1)	//motor code for bar lift going down
		{
			motor[LTLift] = -127;			//motor code for LTLift going down
			motor[LBLift] = -127;			//motor code for LBLift going down
			motor[RTLift] = -127;     //motor code for RTLift going down
			motor[RBLift] = -127;  	  //motor code for RBLift going down

		}

		else												//stop for bar lift
		{
			motor[LTLift] = 0;				//end of motor code for LTLift
			motor[LBLift] = 0;				//end of motor code for LBLift
			motor[RTLift] = 0;    	  //end of motor code for RTLift
			motor[RBLift] = 0;  		  //end of motor code for RBLift
		}

		////////////////////////////////////////////////////////////////////

		if(vexRT[Btn5U] == 1)       //motor code for claw motors picking up
		{
			motor[ClawMotors] = 64;				//motor code for claw motors picking up
		}

		else if(vexRT[Btn5D] == 1)	//motor code for claw motors dropping
		{
			motor[ClawMotors] = -64;			//motor code for claw motors dropping
		}

		else												//stop for claw motors
		{
			motor[ClawMotors] = 0;					// end motor code for claw motors
		}


		////////////////////////////////////////////////////////////////////

		if(vexRT[Btn8U] == 1)       //motor code for Mobile Goal Lift lifting
		{
			motor[MGLiftMotorL] = 127;				//motor code for Mobile Goal Lift lifting
			motor[MGLiftMotorR] = 127;				//motor code for Mobile Goal Lift lifting
		}

		else if(vexRT[Btn8D] == 1)	//motor code for Mobile Goal Lift lowering
		{
			motor[MGLiftMotorL] = -64;			//motor code for Mobile Goal Lift lowering
			motor[MGLiftMotorR] = -64;			//motor code for Mobile Goal Lift lowering
		}

		else												//stop for Mobile Goal Lift motors
		{
			motor[MGLiftMotorL] = 0;					// end motor code for Mobile Goal Lift motors
			motor[MGLiftMotorR] = 0;					// end motor code for Mobile Goal Lift motors
		}

	}
}
