#pragma config(Motor,  port2,           LFront,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LBack,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LClawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RClawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RBack,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[port2]=vexRT[Ch2];
		motor[port3]=vexRT[Ch2];
		motor[port8]=vexRT[Ch3];
		motor[port9]=vexRT[Ch3];

		if(vexRT[Btn6U] == 1)       //motor code for bar lift going up
		{
			motor[port4] = 123;				//motor code for port 4 going up
			motor[port5] = 123;				//motor code for port 5 going up

		}

		else if(vexRT[Btn6D] == 1)	//motor code for bar lift going down
		{
			motor[port4] = -40;				//motor code for port 4 going down
			motor[port5] = -40;				//motor code for port 5 going down

		}

		else												//stop for bar lift
		{
			motor[port4] = 0;         // end motor code for port 4
			motor[port5] = 0;					// end motor code for port 5


		}


		////////////////////////////////////////////////////////////////////

		if(vexRT[Btn5U] == 1)       //motor code for claw opening
		{
			motor[port6] = 63;				//motor code for port 6 opening
			motor[port7] = 63;				//motor code for port 7 opening

		}

		else if(vexRT[Btn5D] == 1)	//motor code for claw closing
		{
			motor[port6] = -40;				//motor code for port 6 closing
			motor[port7] = -40;				//motor code for port 7 closing

		}

		else												//stop for claw motors
		{
			motor[port6] = 0;         // end motor code for port 6
			motor[port7] = 0;					// end motor code for port 7


		}
	}




}
