#pragma config(StandardModel, "RVW CLAWBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
untilBump(dgtl6, 50);


motor[port1]=127;
motor[port10]=127;
wait1Msec(4000);
motor[port1]=0;
motor[port10]=0;

motor[port1]=-127;
motor[port10]=-127;
wait1Msec(4000);
motor[port1]=0;
motor[port10]=0;

}
