#pragma config(Sensor, dgtl1,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  BarLiftEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, Sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           RExtraBarMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RBack,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RBarMotors,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LClawMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RClawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LBack,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LFront,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          LExtraBarMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[RFront] = -95;
	motor[LFront] = -95;
	motor[RBack] = -95;
	motor[LBack] = -95;
	untilEncoderCounts(-200, dgtl1);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[port6] = 127;
	motor[port7] = 127;
	wait1Msec(1800);





	motor[port6] = 60;
	motor[port7] = 60;
	motor[port4] = -123;
	motor[port5] = -123;
	motor[port1] = -123;
	motor[port10] = -123;
	motor[RFront] = -95;
	motor[LFront] = -95;
	motor[RBack] = -95;
	motor[LBack] = -95;
	untilEncoderCounts(-300, dgtl1);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(650);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[port4] = -50;
	motor[port5] = -50;
	motor[port1] = -50;
	motor[port10] = -50;
	motor[RFront] = -75;
	motor[LFront] = 75;
	motor[RBack] = -75;
	motor[LBack] = 75;
	wait1Msec(1050);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[RFront] = 93;
	motor[LFront] = 93;
	motor[RBack] = 93;
	motor[LBack] = 93;
	untilEncoderCounts(400, dgtl1);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	motor[port6] = -123;
	motor[port7] = -123;
	wait1Msec(300);

	motor[port6] = 0;
	motor[port7] = 0;
	wait1Msec(50);



	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;




	wait1Msec(200);
	motor[RFront] = -93;
	motor[LFront] = -93;
	motor[RBack] = -93;
	motor[LBack] = -93;
	untilEncoderCounts(-200, dgtl1);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	wait1Msec(250);
	motor[RFront] = 75;
	motor[LFront] = -75;
	motor[RBack] = 75;
	motor[LBack] = -75;
	wait1Msec(850);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[port4] = 85;
	motor[port5] = 85;
	motor[port1] = 85;
	motor[port10] = 85;
	motor[RFront] = 65;
	motor[LFront] = 65;
	motor[RBack] = 65;
	motor[LBack] = 65;
	untilEncoderCounts(300, dgtl1);


	motor[port4] = 0;
	motor[port5] = 0;
	motor[port1] = 0;
	motor[port10] = 0;
	wait1Msec(50);
	motor[RFront] = -20;
	motor[LFront] = -20;
	motor[RBack] = -20;
	motor[LBack] = -20;
	wait1Msec(50);
	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(1050);




	//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


	//start of second line stuff m8


	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[port6] = 127;
	motor[port7] = 127;
	wait1Msec(1050);

	motor[port6] = 60;
	motor[port7] = 60;
	motor[port4] = -123;
	motor[port5] = -123;
	motor[port1] = -123;
	motor[port10] = -123;
	motor[RFront] = -95;
	motor[LFront] = -95;
	motor[RBack] = -95;
	motor[LBack] = -95;
	untilEncoderCounts(-300, dgtl1);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(650);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[port4] = -50;
	motor[port5] = -50;
	motor[port1] = -50;
	motor[port10] = -50;
	motor[RFront] = -75;
	motor[LFront] = 75;
	motor[RBack] = -75;
	motor[LBack] = 75;
	wait1Msec(1050);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[RFront] = 93;
	motor[LFront] = 93;
	motor[RBack] = 93;
	motor[LBack] = 93;
	untilEncoderCounts(400, dgtl1);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	motor[port6] = -123;
	motor[port7] = -123;
	wait1Msec(300);

	motor[port6] = 0;
	motor[port7] = 0;
	wait1Msec(50);



	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;




	wait1Msec(200);
	motor[RFront] = -93;
	motor[LFront] = -93;
	motor[RBack] = -93;
	motor[LBack] = -93;
	untilEncoderCounts(-200, dgtl1);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	wait1Msec(150);
	motor[RFront] = 75;
	motor[LFront] = -75;
	motor[RBack] = 75;
	motor[LBack] = -75;
	wait1Msec(925);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[port4] = 85;
	motor[port5] = 85;
	motor[port1] = 85;
	motor[port10] = 85;
	motor[RFront] = 65;
	motor[LFront] = 65;
	motor[RBack] = 65;
	motor[LBack] = 65;
	untilEncoderCounts(200, dgtl1);

	wait1Msec(100);
	motor[port4] = 0;
	motor[port5] = 0;
	motor[port1] = 0;
	motor[port10] = 0;
	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(1050);





	///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////





	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[port6] = 127;
	motor[port7] = 127;
	wait1Msec(1050);

	motor[port6] = 60;
	motor[port7] = 60;
	motor[port4] = -123;
	motor[port5] = -123;
	motor[port1] = -123;
	motor[port10] = -123;
	motor[RFront] = -95;
	motor[LFront] = -95;
	motor[RBack] = -95;
	motor[LBack] = -95;
	untilEncoderCounts(-300, dgtl1);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(650);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[port4] = -50;
	motor[port5] = -50;
	motor[port1] = -50;
	motor[port10] = -50;
	motor[RFront] = -75;
	motor[LFront] = 75;
	motor[RBack] = -75;
	motor[LBack] = 75;
	wait1Msec(1050);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[RFront] = 93;
	motor[LFront] = 93;
	motor[RBack] = 93;
	motor[LBack] = 93;
	untilEncoderCounts(400, dgtl1);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	motor[port6] = -123;
	motor[port7] = -123;
	wait1Msec(300);

	motor[port6] = 0;
	motor[port7] = 0;
	wait1Msec(50);



	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;




	wait1Msec(200);
	motor[RFront] = -93;
	motor[LFront] = -93;
	motor[RBack] = -93;
	motor[LBack] = -93;
	untilEncoderCounts(-200, dgtl1);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	wait1Msec(250);
	motor[RFront] = 75;
	motor[LFront] = -75;
	motor[RBack] = 75;
	motor[LBack] = -75;
	wait1Msec(750);

	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

	motor[port4] = 85;
	motor[port5] = 85;
	motor[port1] = 85;
	motor[port10] = 85;
	motor[RFront] = 65;
	motor[LFront] = 65;
	motor[RBack] = 65;
	motor[LBack] = 65;
	untilEncoderCounts(200, dgtl1);

	wait1Msec(100);
	motor[port4] = 0;
	motor[port5] = 0;
	motor[port1] = 0;
	motor[port10] = 0;
	motor[RFront] = 0;
	motor[LFront] = 0;
	motor[RBack] = 0;
	motor[LBack] = 0;
	wait1Msec(50);


	wait1Msec(41237893041132424387241309);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();
	}
}
