#pragma config(Motor,  port2,           LFront,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LBack,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LClawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RClawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RBack,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(5 == 5)
		motor[port1] = vexRT[Ch4];
	motor[port2] = vexRT[Ch3];  //left side front motor
	motor[port3] = vexRT[Ch3];  //left side back motor

	motor[port9] = vexRT[Ch2];  //right side front motor
	motor[port8] = vexRT[Ch2];  //right side back motor


	if(vexRT[Btn6U] == 1)       //motor code for port 4
	{
		motor[port4] = 40;
	}

	else if(vexRT[Btn6D] == 1)
	{
		motor[port4] = -40;
	}

	else
	{
		motor[port4] = 0;         // end motor code for port 4
	}

	if(vexRT[Btn5U] == 1)       //motor code for port 5 and 6
	{
		motor[port5] = 40;
		motor[port6] = 40;
	}

	else if(vexRT[Btn5D] == 1)
	{
		motor[port5] = -40;
		motor[port6] = -40;
	}

	else
	{
		motor[port5] = 0; 				// end motor code for port 5 and 6
		motor[port6] = 0;
	}



}
