#pragma config(Sensor, dgtl1,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11,  Sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           RExtraBarMotor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RBack,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RBarMotors,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LClawMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RClawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LBack,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LFront,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          LExtraBarMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'RO5BOTC' configuration wizard               !!*//

task main()
{

	//////////////Clear sensor values
	SensorValue[dgtl1]=0;
	SensorValue[dgtl3]=0;

}
