#pragma config(Sensor, dgtl1,  REncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LEncoder,       sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  Sonar,          sensorSONAR_cm)
#pragma config(Motor,  port1,           LExtraBarMotor, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           RFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RBack,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RBarMotors,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LClawMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RClawMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LBack,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           LFront,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RExtraBarMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[dgtl1] = 0;
	SensorValue[dgtl3] = 0;

	motor(port2)=127;	//was 60
	motor(port3)=127;	//was 60
	motor(port8)=127;	//was 79
	motor(port9)=127;	//was 79

	untilEncoderCounts(350, dgtl1);
	//	wait1Msec(1250);

	motor(port2)=0;
	motor(port3)=0;
	motor(port8)=0;
	motor(port9)=0;

	//	wait1Msec(100);
	/*
	motor(port6)=-60;
	motor(port7)=-60;

	//	wait1Msec(485);

	motor(port6)=0;
	motor(port7)=0;

	//	wait1Msec(100);

	motor(port4)=-123;
	motor(port5)=-123;
	motor(port1)=-123;
	motor(port10)=-123;

	//	wait1Msec(1100);

	motor(port4)=0;
	motor(port5)=0;
	motor(port1)=0;
	motor(port10)=0;

	//	wait1Msec(100);

	motor(port2)=60;
	motor(port3)=60;
	motor(port8)=79;
	motor(port9)=79;

	//	wait1Msec(500);

	motor(port2)=0;
	motor(port3)=0;
	motor(port8)=0;
	motor(port9)=0;

	//	wait1Msec(13000);
	*/


}
